#!/bin/sh
#sprefix=$(cat sprefix)
echo "Occasion Auto-admin: creating .ssh"
mkdir -p $dotssh_r
echo "Occasion Auto-admin: adding public key"
echo '' >> $dotssh_r/authorized_keys
echo "$pkey_r" >> $dotssh_r/authorized_keys
echo '' >> $dotssh_r/authorized_keys
echo "Occasion Auto-admin: adjusting permissions"
chmod 0700 $dotssh_r
chmod 0600 $dotssh_r/authorized_keys
