#!/bin/sh
echo "Occasion Auto-admin r2: packaging files into ocaa_package"
mkdir ocaa_package
cp -a "$svrex_localstor/$svrex_exec" ocaa_package/"$svrex_exec"
cp -a "$svrex_dbfile" ocaa_package/"$svrex_dbfile"
echo "Occasion Auto-admin r2: sending required files to $user@$hostname:$port"
$xcp -i $id -OCrp -P "$port" $jumpto $customArgs "ocaa_package" $user@$hostname:"ocaa_package_r"
echo "Occasion Auto-admin r2: connecting to $user@$hostname:$port via ssh"
echo "Occasion Auto-admin r2: executing command $svrex_exec $svrex_args"
$xsh -YC -p "$port" $jumpto $fwdruleset -i $id $customArgs $user@"$hostname" -t "cd ocaa_package_r && sh $svrex_exec $svrex_args"
rm -rf ocaa_package/*
