#!/bin/sh
#mkdir mem rmem sproc
unset LD_PRELOAD
cd $ct_system
proot -b /dev -b mem:/dev/shm -b rmem:/run/shm -b /proc -b enconf/fver:/proc/version -b /sys -r . -0 -l --sysvipc /bin/su -lc "cd $ct_workdir && $ct_exec" "$ct_user"
