#!/bin/sh
#fsource="$3"
#fdest="$4"
echo "Occasion File-sharing: connecting to $user@$hostname:$port via ssh"
echo "Occasion File-sharing: retrieving $remotestor/$fsource"
$xcp -i "$id" -OCrp -P "$port" $jumpto "${user}@${hostname}:$remotestor/$fsource" "$localstor/$fdest"
echo "Occasion File-sharing: saved to $localstor/$fdest"
