#!/bin/sh
#This header file defines the variables interpreted by d2efbuild.
#Each variable can be called in a header definition file, to make it easier to define a variable.

#section 1: characters
sq=\'
dq=\"
pchar=\|
redir=\>
bksh=\\
apnd='>>'
nwln=\\\\n

#section 2: utility presets
pos='cut -d'${sq}' '${sq}' -f'
linum='grep -n '$sq'.\?'$sq
ln='head -n1'
tr='tr -d \n'
q86='qemu-system-x86 -machine q35 -cpu max -accel kvm'
q86dev='-device virtio-net-pci,netdev=unet -net user,id=unet -device virtio-scsi-pci'
#fearg: fill empty args
fearg="sed ${sq}s,^$,.,$sq"
sve_a="sed ${dq}s,^$,"
sve_b=",$dq"
sve_d="$pchar $sve_a"
sve_c="$dq $sve_d"
#ssto: Suppress STandard Output
ssto=' > /dev/null'
#se2o: StdErr To stdOut
se2o=' 2>&1'
#bkgr: background
bkgr="${ssto}${se2o} &"

#section 3: (experimental) common patterns
#usage 1: ${sve_load}[variable]${sve_find}${sve_end}
#usage 2: cat [filename] ${sve_file}[pattern]${sve_end}
sve_load="echo ${dq}"
sve_file="$pchar grep ${dq}"
sve_find="$dq $pchar grep ${dq}"
sve_col="${dq} ${pchar} ${ln} $pchar ${pos}"
sve_nc="${dq} ${pchar} ${ln} $pchar ${pos}2-"
sve_np="${dq} ${pchar} ${ln} $pchar ${pos}2- $pchar sed 's,/ *\?$,,'"
sve_end="${dq} ${pchar} ${ln}"
sve_db="${sve_load}\$csdb${sve_find}"
