#!/bin/sh
sh d2efbuild svformat svheader
sh csbuild svheader
rm d2ef.build0 d2ef.builder
rm csbuild.builder
lm=$(cat build/occm_test | wc -l)
cp build/occm_test build/occm_test0
cat build/occm_test0 | sed '$d' | sed '$d' >> build/occm_test
rm build/occm_test0
#echo "$svt" >> build/occm_test
sed -i "$(($lm + 1)),\$s,=.*$,," build/occm_test
sed -i "$(($lm + 1)),\$s,^.*$,echo &="\""\$&"\""," build/occm_test
chmod -R 755 build/
